services:
  - type: web
    name: ats-resume-optimizer
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install && npx puppeteer browsers install chrome && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GROQ_API_KEY
        sync: false
      - key: LLAMA_CLOUD_API_KEY
        sync: false