export const PM_KEYWORDS = [
  'product roadmap',
  'A/B testing',
  'user research',
  'product analytics',
  'stakeholder management',
  'feature prioritization',
  'product strategy',
  'agile',
  'scrum',
  'user stories',
  'go-to-market',
  'MVP',
  'experimentation',
  'KPIs',
  'OKRs',
  'retention',
  'conversion rate',
  'product lifecycle',
  'customer feedback',
  'cross-functional',
];
